R = {
"17N50557": "Motion de censure déposée par la gauche (NFP) contre le gouvernement Barnier. Adoptée, elle aurait obligé le Gouvernement à démissionner.",
"17N50173": "Texte comptable annuel : le Parlement approuve les comptes de la Sécurité sociale pour 2023 (recettes, dépenses, déficits des régimes).",
"17N50450": "Reporte les élections provinciales en Nouvelle-Calédonie, pour laisser le temps de trouver un accord politique sur l'avenir de l'archipel.",
"17N50453": "Proposition du RN pour revenir sur la réforme des retraites de 2023 et abaisser l'âge de départ et la durée de cotisation exigée.",
"17N50172": "Loi de « règlement » : le Parlement constate l'exécution réelle du budget de l'État en 2023 et approuve les comptes.",
"17N50838": "Ajuste en fin d'année les crédits et recettes du budget 2024 de l'État (collectif budgétaire de « fin de gestion »).",
"17N50168": "Réforme le financement de l'audiovisuel public (France Télévisions, Radio France…) après la suppression de la redevance.",
"17N50588": "Budget annuel de la Sécurité sociale pour 2025 : recettes, dépenses de santé, retraites, famille, et objectifs de déficit.",
"16N50082": "Texte de procédure pénale : encadre le moment où l'on peut encore contester la régularité d'une procédure (« purge des nullités »).",
"17N50820": "Prolonge la possibilité d'utiliser les titres-restaurant pour acheter tout produit alimentaire en supermarché, même non consommable immédiatement.",
"17N50198": "Budget de l'État pour 2025 : impôts, dépenses de chaque ministère, niveau de déficit et d'emprunt.",
"17N51256": "Motion de censure déposée par LFI contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N50604": "Crée un centre hospitalier universitaire (CHU) en Corse, seule région sans CHU, pour améliorer l'accès aux soins et former des médecins sur place.",
"17N51079": "Loi spéciale de secours : faute de budget voté à temps, elle autorise l'État à continuer de lever l'impôt et d'emprunter en attendant.",
"16N49258": "Encadre et plafonne les frais que les banques facturent aux héritiers pour clôturer les comptes d'une personne décédée.",
"17N50370": "Fait rembourser intégralement les fauteuils roulants par l'Assurance maladie, pour supprimer le reste à charge des personnes handicapées.",
"17N50779": "Mesures d'urgence contre la vie chère en outre-mer : contrôle des prix et limitation de la concentration des grands groupes de distribution.",
"17N50915": "Adapte les règles de gouvernance des chambres d'agriculture et de la Mutualité sociale agricole (MSA).",
"17N51222": "Mesures d'urgence après le cyclone Chido (décembre 2024) : reconstruction accélérée de Mayotte, dérogations et soutien aux habitants.",
"17N50778": "Étend le repas à 1 € au restaurant universitaire à tous les étudiants, pas seulement aux boursiers.",
"17N50444": "Renforce la protection des parents d'enfants atteints d'un cancer, d'une maladie grave ou d'un handicap (congés, emploi, aides).",
"17N50777": "Oblige à réparer plus vite les ascenseurs en panne dans les immeubles, pour éviter l'isolement des habitants.",
"16N46650": "Impose un nombre minimum de soignants par patient à l'hôpital, pour garantir la sécurité et la qualité des soins.",
"17N50636": "Autorise, sous conditions, l'épandage de produits de traitement des cultures par drones.",
"17N50775": "Mesures d'urgence sur les crèches privées à but lucratif après les révélations du livre « Les Ogres » : contrôles, encadrement, transparence.",
"17N51017": "Renforce la lutte contre les violences faites aux femmes et aux enfants (prévention, protection des victimes, sanctions).",
"17N51427": "Recours au 49.3 sur le budget de la Sécurité sociale 2025. Le vote porte sur la motion de censure qui en découle.",
"17N50715": "Renforce les moyens de détecter et de sanctionner les fraudes aux aides publiques (aides sociales, aux entreprises, à la rénovation…).",
"17N50911": "Réserve la vente de protoxyde d'azote (« gaz hilarant ») aux professionnels et renforce la prévention contre son usage détourné.",
"16N49801": "Fait prendre en charge intégralement par l'Assurance maladie les soins liés au cancer du sein, pour supprimer le reste à charge.",
"17N51462": "Recours au 49.3 sur une partie du budget de la Sécurité sociale 2025. Le vote porte sur la motion de censure qui en découle.",
"17N51475": "Recours au 49.3 sur l'ensemble du budget de la Sécurité sociale 2025. Le vote porte sur la motion de censure qui en découle.",
"16N46655": "Interdit les cigarettes électroniques jetables (« puffs »), pour des raisons de santé publique et d'environnement.",
"17N51039": "Durcit les conditions d'accès à la nationalité française par le droit du sol à Mayotte, face à la pression migratoire.",
"16N49796": "Améliore la prise en charge de la maladie de Charcot (SLA) et d'autres maladies graves évolutives (accès plus rapide aux aides).",
"16N49843": "Permet d'élire le maire d'une commune nouvelle même si le conseil municipal est incomplet.",
"17N51540": "Motion de censure déposée par le groupe socialiste contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N50690": "Durcit la justice des mineurs délinquants (procédures plus rapides, sanctions) et renforce la responsabilité des parents.",
"17N51161": "Prolonge un dispositif expérimental qui facilite l'accès des jeunes de milieux modestes aux concours des écoles de la fonction publique.",
"17N53702": "Texte sur la souveraineté alimentaire : défendre la capacité de la France à produire sa propre nourriture.",
"17N51215": "Crée un impôt plancher de 2 % sur les fortunes de plus de 100 millions d'euros (« taxe Zucman »).",
"16N49176": "Renforce la sécurité dans les transports en commun (pouvoirs des agents de sûreté, caméras, sanctions).",
"17N51563": "Encadre le démarchage téléphonique : il ne serait autorisé qu'avec le consentement préalable du consommateur.",
"17N51346": "Crée un statut pour les médecins, infirmiers et autres soignants des services d'incendie et de secours (pompiers).",
"17N51328": "Crée une amende pour les vignes abandonnées, foyers de maladies (flavescence dorée) qui menacent les vignobles voisins.",
"17N51453": "Facilite l'ouverture d'un café ou bar (licence IV) dans les communes de moins de 3 500 habitants qui n'en ont plus.",
"17N51329": "Simplifie la sortie de l'indivision entre héritiers, pour débloquer des successions et remettre des logements vacants sur le marché.",
"17N51002": "Réforme la profession d'infirmier : mieux reconnaître ses missions et élargir ses compétences (consultations, prescriptions).",
"16N49472": "Organise la lutte contre le frelon asiatique pour protéger les abeilles et la filière apicole.",
"17N50452": "Proposition de résolution demandant la publication des cahiers de doléances du grand débat national de 2019.",
"17N51312": "Lutte contre la disparition des terres agricoles et encadre la hausse des prix du foncier agricole.",
"17N51467": "Proposition de résolution européenne appelant à renforcer le soutien à l'Ukraine face à l'invasion russe.",
"16N49927": "Assouplit la gestion des compétences « eau » et « assainissement » entre les communes et les intercommunalités.",
"17N51504": "Rééquilibre les négociations commerciales entre industriels de l'agroalimentaire et grande distribution (prolongement des lois Egalim).",
"17N51279": "Proposition de résolution créant une commission d'enquête sur les effets psychologiques de TikTok sur les mineurs.",
"17N51078": "Crée le statut d'un procureur national spécialisé contre le narcotrafic et la criminalité organisée.",
"17N50589": "Met en place une stratégie nationale de prévention du « chemsex » (usage de drogues lors de rapports sexuels).",
"17N51480": "Supprime la notion de « devoir conjugal » invoquée dans certains divorces, après une condamnation de la France par la CEDH.",
"17N51349": "Intègre la notion de non-consentement dans la définition pénale du viol et des agressions sexuelles.",
"17N50169": "Loi contre le narcotrafic : parquet national spécialisé, nouveaux outils d'enquête, régime carcéral renforcé pour les gros trafiquants.",
"17N51376": "Proposition de résolution pour accueillir en France un Institut de l'Océan de l'université des Nations unies.",
"17N50796": "Texte technique d'adaptation du droit français à de nombreuses règles européennes (finance, énergie, transports, santé…).",
"17N51510": "Renforce le contrôle du Parlement lorsqu'un gouvernement démissionnaire se contente d'expédier les affaires courantes.",
"17N51518": "Valorise les réserves communales de sécurité civile, ces bénévoles qui aident la commune lors des crises (inondations, incendies…).",
"17N50631": "Vise à faire exécuter réellement les courtes peines de prison ferme, en limitant leur aménagement systématique.",
"17N51014": "Mesures pour augmenter le nombre d'orthophonistes et réduire les listes d'attente des patients.",
"17N50579": "Généralise le scrutin de liste paritaire aux élections municipales, y compris dans les petites communes.",
"17N50692": "Réforme la loi « PLM » : les habitants de Paris, Lyon et Marseille éliraient directement leur maire, comme ailleurs.",
"17N51485": "Permet de convertir les dernières centrales à charbon vers des combustibles moins polluants, en préservant les emplois.",
"17N50686": "Améliore la scolarisation des élèves en situation de handicap (accompagnants, parcours adapté).",
"16N49868": "Projet de loi de simplification administrative pour les entreprises : moins de formalités et de démarches.",
"17N50689": "Protège contre les discriminations au travail les personnes engagées dans une PMA ou une adoption.",
"15N43846": "Étend la parité femmes-hommes aux petites communes et aux exécutifs des intercommunalités.",
"17N51852": "Simplifie le droit de l'urbanisme et du logement pour accélérer les projets de construction.",
"17N51716": "Renforce les droits des victimes dont la plainte est classée sans suite (information, recours).",
"17N51849": "Mesures contre la hausse de la mortalité infantile en France, qui progresse depuis 2020.",
"17N50413": "Crée une décoration, la « croix de la valeur », pour récompenser l'engagement des sapeurs-pompiers.",
"17N50724": "Renforce la lutte contre l'antisémitisme dans les universités (prévention, sanctions disciplinaires).",
"17N51516": "Proposition transpartisane contre les déserts médicaux, notamment en régulant l'installation des médecins.",
"17N50627": "Renforce la lutte contre la pédocriminalité, notamment en ligne (sollicitation de mineurs, images pédopornographiques).",
"17N51672": "Développe les soins palliatifs et l'accompagnement des malades en fin de vie (reprend une partie du projet de loi de 2024).",
"17N51670": "Crée un droit à l'aide à mourir, encadré par des conditions strictes, pour certains malades en fin de vie.",
"17N51702": "Déclare d'intérêt public majeur l'autoroute Castres-Toulouse, pour sécuriser juridiquement le chantier contesté.",
"17N50819": "Lève des contraintes administratives et environnementales pesant sur les agriculteurs (loi « Duplomb »).",
"17N52167": "Motion de censure déposée par LFI contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N51973": "Maintient les seuils actuels de TVA des micro-entrepreneurs, pour annuler l'abaissement prévu à 25 000 € de chiffre d'affaires.",
"17N51499": "Reconnaissance par la Nation des rapatriés d'Indochine accueillis dans des conditions indignes, et réparation des préjudices.",
"17N51052": "Porte sur le vote par correspondance des personnes détenues.",
"16N48739": "Crée le délit d'« homicide routier » pour les conducteurs responsables d'un décès après une faute grave (alcool, drogue, vitesse).",
"17N51999": "Abroge la réforme des retraites de 2023, pour revenir sur le report de l'âge légal de 62 à 64 ans.",
"17N52245": "Proposition de résolution créant une commission d'enquête sur l'accès à la justice en outre-mer.",
"17N51132": "Permet aux salariés de donner leur sang, leurs plaquettes ou leur plasma sur leur temps de travail.",
"17N51979": "Verse les allocations familiales dès le premier enfant, et non plus à partir du deuxième.",
"17N51115": "Expérimente l'encadrement des loyers et des mesures pour améliorer l'habitat dans les outre-mer.",
"17N51362": "Ratifie un amendement à un traité international contre la pollution des mers par l'immersion de déchets.",
"17N52133": "Texte comptable annuel : le Parlement approuve les comptes de la Sécurité sociale pour 2024.",
"17N52408": "Motion de censure déposée par le groupe socialiste contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"16N49299": "Renforce la sécurité des soignants et des professionnels de santé, avec des sanctions aggravées en cas d'agression.",
"16N49849": "Fixe la programmation énergétique nationale (nucléaire, renouvelables) et simplifie les règles du secteur de l'énergie.",
"17N53195": "Budget de l'État pour 2026 : impôts, dépenses des ministères, déficit et emprunt.",
"17N51984": "Réforme institutionnelle de Mayotte en « Département-Région ».",
"17N51429": "Permet de maintenir plus longtemps en rétention, à l'issue de leur peine, certains étrangers condamnés pour des faits très graves et jugés dangereux.",
"17N51985": "Programme de refondation de Mayotte après le cyclone Chido : investissements, reconstruction, lutte contre l'immigration irrégulière.",
"17N52040": "Transpose des accords entre syndicats et patronat : emploi des seniors (« salariés expérimentés ») et dialogue social.",
"16N47697": "Réforme la gouvernance de l'audiovisuel public (rapprochement des sociétés) et renforce la « souveraineté audiovisuelle ».",
"17N52719": "Proposition de résolution demandant de dénoncer l'accord franco-algérien de 1968, qui fixe des règles de séjour spécifiques aux Algériens.",
"17N52787": "Rend obligatoire l'indication de l'origine des produits alimentaires sur l'étiquette.",
"17N53073": "Proposition de résolution demandant au Gouvernement de s'opposer à l'accord de libre-échange UE-Mercosur.",
"17N52976": "Garantit l'égalité d'accès à La Poste en outre-mer (tarifs, délais, présence postale) par rapport à l'Hexagone.",
"17N52922": "Budget annuel de la Sécurité sociale pour 2026 : santé, retraites, famille, avec des mesures pour réduire le déficit.",
"17N53135": "Ajuste en fin d'année les crédits et recettes du budget 2025 de l'État (collectif de « fin de gestion »).",
"17N52655": "Reporte à nouveau les élections provinciales en Nouvelle-Calédonie pour appliquer l'accord politique du 12 juillet 2025.",
"17N52977": "Nationalise ArcelorMittal France pour préserver la sidérurgie française et ses emplois face au désengagement du groupe.",
"17N51457": "Organise la protection sociale complémentaire (mutuelle, prévoyance) des agents des collectivités territoriales.",
"17N53051": "Protège les mineurs isolés et vise à ce qu'aucun enfant ne dorme à la rue.",
"17N52781": "Garantit à chaque enfant suivi par le juge des enfants (assistance éducative) le droit d'être assisté d'un avocat.",
"17N51173": "Modifie un point technique du statut d'autonomie de la Polynésie française (article 43, compétences des communes).",
"17N53069": "Pérennise l'encadrement des loyers dans les villes tendues, dont l'expérimentation devait s'arrêter en novembre 2026.",
"17N52428": "Budget de l'État pour 2026 : impôts, dépenses des ministères, déficit et emprunt.",
"17N52749": "Rend automatique le renouvellement des titres de séjour de longue durée des étrangers en situation régulière.",
"17N53058": "Mesures d'urgence contre la vie chère en outre-mer dans les services (banque, télécoms, transport aérien…).",
"16N49280": "Crée un statut de l'élu local : indemnités, formation, conciliation avec l'emploi, protection.",
"17N53516": "Motion de censure déposée par LFI contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N52100": "Organise les Jeux olympiques et paralympiques d'hiver de 2030 dans les Alpes françaises (sécurité, chantiers, dérogations).",
"17N51351": "Reconnaît le préjudice subi par les femmes condamnées pour avortement avant la loi Veil de 1975.",
"17N53517": "Motion de censure déposée par le Rassemblement national contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N53386": "Loi spéciale de secours : faute de budget 2026 voté à temps, elle autorise l'État à lever l'impôt et à emprunter.",
"17N51968": "Facilite l'accès au logement des agents publics (soignants, enseignants, policiers…) près de leur lieu de travail.",
"17N53300": "Suspend la création de nouvelles agences et instances administratives, pour freiner la dispersion et le coût de l'État.",
"16N46127": "Reconnaît et indemnise les personnes condamnées pour homosexualité en France entre 1945 et 1982.",
"17N53187": "Protège les mineurs sur les réseaux sociaux (âge minimum, vérification, obligations des plateformes), après le rapport sur TikTok.",
"17N53005": "Proposition de résolution créant une commission d'enquête sur le traitement judiciaire de l'inceste et la situation des parents protecteurs.",
"17N51962": "Pérennise et étend « Territoires zéro chômeur de longue durée », qui crée des emplois pour les personnes durablement privées de travail.",
"17N53279": "Inscrit dans la loi que le mariage n'impose aucune obligation de relations sexuelles (fin du « devoir conjugal »).",
"17N52746": "Crée une « foncière de l'État » chargée de gérer ses bâtiments, pour réduire les surfaces de bureaux et rénover le parc.",
"17N53158": "Permet aux commerçants d'utiliser des outils numériques (vidéo, signalement) pour lutter contre le vol à l'étalage.",
"17N51845": "Répare le préjudice des « enfants de la Creuse », mineurs réunionnais déplacés de force vers l'Hexagone entre 1962 et 1984.",
"17N53689": "Recours au 49.3 sur le budget 2026 en lecture définitive. Le vote porte sur la motion de censure qui en découle.",
"17N52744": "Rend gratuits les parkings des hôpitaux publics pour les patients, les visiteurs et le personnel.",
"17N51655": "Réforme la protection de l'enfance pour mieux placer l'intérêt de l'enfant au centre des décisions.",
"17N53378": "Proposition de résolution demandant la libération des prisonniers arméniens détenus par l'Azerbaïdjan.",
"17N53530": "Change le régime juridique des barrages hydroélectriques pour relancer les investissements, sans remise en concurrence.",
"17N53821": "Motion de censure déposée par le Rassemblement national contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N53192": "Permet aux médecins ayant commencé leurs études au Royaume-Uni avant le Brexit d'exercer en France.",
"17N53427": "Protège mieux les personnes menacées par les réseaux de narcotrafic (témoins, militants, proches), après l'assassinat de Mehdi Kessaci.",
"17N53822": "Motion de censure déposée par LFI contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N51720": "Permet aux commerçants d'utiliser des outils numériques pour lutter contre le vol à l'étalage.",
"17N51713": "Permet aux mairies de préempter les commerces détenus via des SCI, pour préserver la diversité commerciale des centres-villes.",
"17N51175": "Aide les collectivités à prévenir et à gérer les inondations (financement, compétences).",
"17N51330": "Renforce les « droits voisins » : les plateformes numériques (Google, Meta…) doivent mieux rémunérer la presse.",
"17N52985": "Renforce la lutte contre les fraudes sociales et fiscales (contrôles, partage d'informations, sanctions).",
"17N53715": "Sécurise le foncier agricole et adapte le travail des agriculteurs au changement climatique.",
"17N53672": "Inscrit dans la loi un enseignement de défense nationale pour les élèves.",
"17N53720": "Renforce le contrôle, la gouvernance et la responsabilité financière des agences et opérateurs de l'État.",
"17N53690": "Permet de rembourser aux candidats aux élections les honoraires de leur expert-comptable.",
"17N52230": "Garantit aux parlementaires et aux bâtonniers le droit de visiter les lieux de privation de liberté (prisons, centres de rétention…).",
"17N52984": "Révision de la Constitution pour mettre en œuvre l'accord de 2025 sur l'avenir institutionnel de la Nouvelle-Calédonie.",
"17N53067": "Reconnaît une politique nationale d'adaptation au changement climatique et adapte l'assurance face aux catastrophes naturelles.",
"17N53775": "Encadre les regroupements d'écoles entre communes rurales, pour garantir l'égalité d'accès à l'école.",
"17N52750": "Remplace départements et régions par une collectivité unique là où c'est voulu, pour simplifier le « millefeuille » territorial.",
"17N51711": "Renforce les sanctions contre l'organisation de rave-parties illégales.",
"17N53770": "Simplifie les règles des marchés publics pour les acheteurs publics et les entreprises.",
"17N51987": "Permet aux salariés de certains commerces et services (boulangeries, fleuristes…) de travailler le 1er mai.",
"17N53315": "Crée une procédure simplifiée pour recouvrer les factures impayées non contestées entre entreprises.",
"17N52635": "Facilite la restitution de biens culturels pris illégalement à d'autres pays, notamment pendant la colonisation.",
"17N53284": "Renforce la sécurité et allonge les possibilités de rétention administrative des étrangers dangereux sous OQTF, après l'attentat de Mulhouse.",
"17N52208": "Soutient le développement des navires à propulsion par la voile pour décarboner le transport maritime.",
"17N54083": "Actualise la loi de programmation militaire 2024-2030 : moyens et équipements des armées revus à la hausse.",
"17N52743": "Oblige à informer les victimes de violences sexuelles de la libération de leur agresseur, et à les protéger.",
"17N52924": "Programme de soutien à la recherche de traitements contre les cancers et les maladies rares de l'enfant.",
"17N52104": "Met à jour la liste des électeurs autorisés à voter aux élections provinciales de Nouvelle-Calédonie.",
"17N53357": "Étend à toutes les communes la compensation financière pour la gestion du service public de la petite enfance.",
"17N54006": "Loi pour la montagne : adaptation au réchauffement (eau, pastoralisme, tourisme, logement) et soutien aux territoires de montagne.",
"17N54144": "Mobilise les logements existants (vacants, à rénover, copropriétés dégradées) pour répondre à la crise du logement.",
"17N51791": "Pérennise un contrat de professionnalisation expérimental, plus souple, pour former en alternance les personnes éloignées de l'emploi.",
"17N52767": "Abroge symboliquement le Code noir, l'édit de 1685 qui réglementait l'esclavage dans les colonies françaises.",
"17N54227": "Protège les enfants contre les violences en milieu scolaire (contrôle des établissements, signalements).",
"17N54085": "Loi d'urgence agricole : protection et souveraineté de la production agricole française.",
"17N53159": "Renforce les moyens de l'agence qui gère et revend les biens saisis aux criminels, et facilite le travail des experts judiciaires.",
"17N54148": "Réduit l'exposition de la population au cadmium, un métal toxique présent dans l'alimentation (engrais).",
"17N53981": "Transpose un accord entre syndicats et patronat modifiant les règles de l'assurance chômage.",
"17N51775": "Garantit l'interdiction de la vaisselle en plastique dans les cantines accueillant des enfants et en crèche.",
"16N49263": "Reconnaît la responsabilité de l'État et indemnise les victimes du chlordécone, pesticide utilisé aux Antilles.",
"17N51955": "Revalorise les pensions de retraite des agriculteurs, dans la lignée des lois « Chassaigne ».",
"17N53053": "Mesures pour protéger la santé mentale des agriculteurs et prévenir les suicides dans le monde agricole.",
"17N54196": "Loi de « règlement » : constate l'exécution réelle du budget de l'État en 2025 et approuve les comptes.",
"17N51981": "Améliore le minimum vieillesse (ASPA) pour les retraités les plus pauvres.",
"17N54229": "Réforme les bourses étudiantes sur critères sociaux pour lutter contre la précarité des étudiants.",
"17N54373": "Texte comptable annuel : le Parlement approuve les comptes de la Sécurité sociale pour 2025.",
"17N53600": "Autorise la Martinique à fixer elle-même certaines règles en matière d'énergie, d'eau et d'assainissement.",
"17N54218": "Révision de la Constitution pour donner à la Corse un statut d'autonomie au sein de la République.",
"17N54613": "Motion de censure déposée par les écologistes et la gauche contre le Gouvernement. Adoptée, elle aurait renversé le Gouvernement.",
"17N51732": "Réforme l'organisation, la gouvernance et le financement du sport professionnel (droits TV, ligues).",
"17N53942": "Loi organique accompagnant la réforme de la justice criminelle (organisation des juridictions qui jugent les crimes).",
"17N53940": "Réforme de la justice criminelle : jugement des crimes plus rapide et meilleure place des victimes dans la procédure.",
"17N51037": "Crée une présomption de légitime défense pour les policiers et gendarmes lorsqu'ils font usage de leur arme en service.",
"16N49364": "Freine la « mode éphémère » (Shein, Temu…) : pénalités environnementales et interdiction de la publicité.",
"17N53980": "Réponses rapides aux troubles à l'ordre public du quotidien (rodéos, squats, rassemblements…) : nouveaux pouvoirs et sanctions.",
"17N54372": "Réforme de la protection de l'enfance et de l'Aide sociale à l'enfance (380 000 enfants pris en charge).",
"17N53426": "Stratégie nationale de prévention des maladies cardio-neuro-vasculaires, 2e cause de décès en France.",
}
